const holes = document.querySelectorAll('.hole')
const scoreBoard = document.querySelectorAll('.score')
const moles = document.querySelectorAll('.mole')

let lastHole
let score = 0;
let timeUp = false;

// generates random amount of time
function randTime(min, max) {
  return Math.round(Math.random() * (max - min) + 200);
}

// get random hole at a time
function randHole(holes) {
  //choose a random index between 0 and holes.length and round down
  const index = Math.floor(Math.random() * holes.length);
  const hole = holes[index];

  // we do not want same hole twice in a role. If it's, we n
  if (hole === lastHole) {
    return randHole(holes);
  }

  lastHole = hole
  return hole;
}

function popUp() {
  const time = randTime(300, 1200);
  const hole = randHole(holes);
  hole.classList.add('up');
  setTimeout(() => {
    hole.classList.remove('up');
    if (!timeUp) popUp();
  }, time);
}


function startGame() {
  // set score back to 0 when game starts
  scoreBoard.textContent = 0;
  timeUp = false;
  score = 0;
  popUp();
  setTimeout(() => timeUp = true, 12000);
}

function target(e) {
  // true when the event was generated by a user action
  // and false when the event was created or modified by a script or dispatched via dispatchEvent.
  if (!e.isTrusted) return;

  // increment score when a mole is targetted
  score++;
  console.log(score);
  debugger
  this.classList.remove("up");

  // update score to show total hits
  scoreBoard.textContent = score;
}

moles.forEach(mole => mole.addEventListener('click', target));
